name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Watch..
      run: |
          echo "watching..."
          curl -sfL https://get.k3s.io | sh -
          sleep 1
          k3s kubectl get po -A
          sleep 2
          k3s kubectl get po -A
          sleep 3
          k3s kubectl get po
        
