name: RunK3s

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: debianmaster/actions-k3s@master # 使用k3s提供的k8s环境
      id: k3s
      with:
        version: 'v1.21.2-k3s1'
    - run: |
        sleep 10
        pwd
        kubectl get po -A
        kubectl get nodes

      
    - uses: actions/checkout@v2
      name: checkout
      with:
        ref: main
    - run: |
          ls
          echo "begin download"
          wget ${{secrets.FILE_SERVER}}/files/frp_0.33.0_linux_amd64.tar.gz
          echo "done download"
          ls
          tar -xvf frp_0.33.0_linux_amd64.tar.gz
          ls
          cd frp_0.33.0_linux_amd64
          ls
          rm -f frpc.ini
          wget ${{secrets.FILE_SERVER}}/files/frpc.ini
          mkdir -p  ~/.ssh
          echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDqbZGPzT/pBmmCF11NNVQbzQQZ6AFCNAuqeuKB1a3G2Rk8IvRhkugXvzT5fPd+Zu+ywdxEBRMc084f9wGgNUIZsGmUkzCu7akpO9kXuBXrKSj1s6WkA953lpBcz0cpiMZZSlcfumTKcA/pQXS21Hqa1r/vWdrkNDF8oxrI3DEm6/cfxBjiqXo/mr8xVKFRF0ZihhJOCVNIbIRRfg6Zh2cKIBKZ+Njy4MAB1UfYsvv9x/Nn1RnpZVR47rju55WcgTOqEBJMatgu77nmdV0Z7whcMQ+YaJ8l+9XE97JN/NwhE9Z5bo5hc7Ze5ztgi/k3KDh11fNJMnKp/UU66KSuFjhV liangyuanpeng@163.com' > ~/.ssh/authorized_keys
          ./frpc -c frpc.ini
          sh req.sh
