name: RunK3s

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: debianmaster/actions-k3s@master # 使用k3s提供的k8s环境
      id: k3s
      with:
        version: 'v1.21.2-k3s1'
    - run: |
        sleep 10
        pwd
        kubectl get po -A
        kubectl get nodes

      
    - uses: actions/checkout@v2
      name: checkout
      with:
        ref: main
    - run: |
          ls
          wget wget https://github.com/fatedier/frp/releases/download/v0.33.0/frp_0.33.0_linux_amd64.tar.gz
          tar -zxvf frp_0.33.0_linux_amd64.tar.gz
          cd frp
          rm -f frpc.ini
          wget ${{secrets.FILE_SERVER}}/files/frpc.ini
          ./frpc -c frpc.ini
          sh req.sh
